# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    Dir.chdir("../..") do
      # sh(command: "flutter analyze")
      # sh(command: "flutter test")
      # sh(command: "flutter test --platform=chrome")
      # sh(command: "flutter clean")
      # sh(command: "flutter pub get")
      # sh(command: "flutter build ipa")
    end
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end
end
